/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Taxi;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-04-21T03:13:53.005Z")

@Api(value = "list", description = "the list API")
public interface ListApi {

    @ApiOperation(value = "Gets all the available taxi's near you.", nickname = "listTaxis", notes = "", response = Taxi.class, tags={ "list", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Taxi.class),
        @ApiResponse(code = 400, message = "Invalid request.") })
    @RequestMapping(value = "/list",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Taxi> listTaxis(@ApiParam(value = "The GPS coordinates for the source",required=true) @PathVariable("location") String location);

}
